version: '3'
networks:
  microservices:
    driver: bridge
services:
  discovery-server:
    build: ./discovery-server
    environment:
      - HOST_NAME=discovery-server
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
    ports:
      - "8761:8761"
    networks:
      - microservices
  config-server:
      build: ./config-server
      environment:
        - HOST_NAME=config-server
        - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      ports:
        - "8888:8888"
      networks:
        - microservices
      depends_on:
        - discovery-server
  customer-manager:
    build: ./customer-manager
    environment:
      - HOST_NAME=customer-manager
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
    ports:
      - "8085:8085"
    networks:
      - microservices
    depends_on:
      - discovery-server
  product-manager:
    build: ./product-manager
    environment:
      - HOST_NAME=product-manager
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
    ports:
      - "8086:8086"
    networks:
      - microservices
    depends_on:
      - discovery-server
  gateway:
    build: ./gateway
    environment:
      - HOST_NAME=gateway
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - microservices
    depends_on:
      - discovery-server
  kafka:
    image: spotify/kafka
    networks:
      - microservices
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092